AWSTemplateFormatVersion: '2010-09-09'
Description: 'Module 10 Demo Setup - Data Security and System Auditing'

Resources:

  SecurityAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: security-alerts-demo

  SecurityAlertsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics: [!Ref SecurityAlertsTopic]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [events.amazonaws.com, cloudwatch.amazonaws.com]
            Action: sns:Publish
            Resource: !Ref SecurityAlertsTopic

  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Mod10-EventBridgeRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: {Service: events.amazonaws.com}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowSNSPublish
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource: !Ref SecurityAlertsTopic

Outputs:
  SecurityAlertsTopicArn: {Value: !Ref SecurityAlertsTopic}

